ペットショップ1課題完了
chie-hirabayashi/pet_shop pull request #1
Opened 2022-07-26 13:56 UTC by chie-hirabayashi

すみません。
ブランチ切り替え忘れて、作成してしまいました。。
作成後にブランチ切り替えて、フォーマッターをかけてpushしています。
ご確認よろしくお願いいたします。

2022-07-26 22:56 UTC, naoto1192 requested changes
コメントしましたのでご確認ください！

2022-07-26 22:56 UTC, naoto1192 commented on index.php
> -<?php
`index.php`にアクセスしたときに、問題文にあります画面が表示されるよう記入してみてください😊

2022-07-27 08:34 UTC, chie-hirabayashi commented
お疲れさまです。
ちゃんと問題読んでませんでした(T_T)
よろしくお願いいたします。

2022-07-27 08:50 UTC, naoto1192 approved these changes
お疲れさまでした！
問題ありませんので、マージしてOKです😉
![687474703a2f2f692e696d6775722e636f6d2f663063745378502e676966](https://user-images.githubusercontent.com/98454350/181204610-5e2db256-0409-4d0d-88cb-e79a92d0e871.gif)

2022-07-27 13:20 UTC, merged